import { Package, Payment, Provider, Service } from "./payment"

export const PAYMENTS: Payment[] = [
  {name: "airtime", route: 'airtime', packages: [
    { serviceName: 'MTN', serviceRoute: 'mtn', serviceType: "airtime"},
    { serviceName: 'GLO', serviceRoute: 'glo', serviceType: "airtime"},
    { serviceName: '9mobile', serviceRoute: '9mobile', serviceType: "airtime" },
    { serviceName: 'AIRTEL', serviceRoute: 'airtel', serviceType: "airtime" },]},

  {name: "internet", route: "internet-bills", packages: [
    { serviceName: 'spectranet', serviceRoute: 'spectranet-limited', serviceType: "internet" },
    { serviceName: 'smile bundle', serviceRoute: 'smile-bundle', serviceType: "internet" },
    { serviceName: 'ipnx subscription', serviceRoute: 'ipnx-subscription-payments', serviceType: "internet" },
    { serviceName: 'Mtn Vtu Plus Data', serviceRoute: 'mtn-vtu-plus-data', serviceType: "internet" },
    { serviceName: '9Mobile-recharge(etop Up)', serviceRoute: '9Mobile-recharge-e-top-up', serviceType: "internet" },
    { serviceName: 'Airtel Prepaid Data Bundle', serviceRoute: 'airtel-prepaid-data-bundle', serviceType: "internet" },
    { serviceName: 'Airtel Voice, Data & Sms Bundles', serviceRoute: 'airtel-voice-data-sms-bundles', serviceType: "internet" },
    { serviceName: 'Glo Data Bundle', serviceRoute: 'glo-data-bundle', serviceType: "internet" },
  ]},
  {name: "electricity", route: "electricity", packages: [
    { serviceName: 'Benin EDC', serviceRoute: 'benin-edc', serviceType: "electricity" },
    { serviceName: 'Enugu EDC', serviceRoute: 'enugu-edc', serviceType: "electricity" },
    { serviceName: 'Eko EDC', serviceRoute: 'eko-edc', serviceType: "electricity" },
    { serviceName: 'Ibadan EDC', serviceRoute: 'ibadan-edc', serviceType: "electricity" },
    { serviceName: 'Ikeja EDC', serviceRoute: 'ikeja-edc', serviceType: "electricity" },
    { serviceName: 'Jos EDC', serviceRoute: 'jos-edc', serviceType: "electricity" },
    { serviceName: 'Kaduna EDC', serviceRoute: 'kaduna-edc', serviceType: "electricity" },
    { serviceName: 'Abuja EDC', serviceRoute: 'abuja-edc', serviceType: "electricity" },
    { serviceName: 'Kedco', serviceRoute: 'kedco', serviceType: "electricity" },
    { serviceName: 'PHed Postpaid', serviceRoute: 'phed-postpaid', serviceType: "electricity" },
  ],}


]

export const PROVIDERS: Service[] = [
  { serviceName: 'MTN', serviceRoute: 'mtn', serviceType: "airtime"},
  { serviceName: 'GLO', serviceRoute: 'glo', serviceType: "airtime"},
  { serviceName: '9mobile', serviceRoute: '9mobile', serviceType: "airtime" },
  { serviceName: 'AIRTEL', serviceRoute: 'airtel', serviceType: "airtime" },

  { serviceName: 'spectranet', serviceRoute: 'spectranet-limited', serviceType: "internet" },
  { serviceName: 'smile bundle', serviceRoute: 'smile-bundle', serviceType: "internet" },
  { serviceName: 'ipnx subscription', serviceRoute: 'ipnx-subscription-payments', serviceType: "internet" },
  { serviceName: 'Mtn Vtu Plus Data', serviceRoute: 'mtn-vtu-plus-data', serviceType: "internet" },
  { serviceName: '9Mobile-recharge(etop Up)', serviceRoute: '9Mobile-recharge-e-top-up', serviceType: "internet" },
  { serviceName: 'Airtel Prepaid Data Bundle', serviceRoute: 'airtel-prepaid-data-bundle', serviceType: "internet" },
  { serviceName: 'Airtel Voice, Data & Sms Bundles', serviceRoute: 'airtel-voice-data-sms-bundles', serviceType: "internet" },
  { serviceName: 'Glo Data Bundle', serviceRoute: 'glo-data-bundle', serviceType: "internet" },
  { serviceName: 'benin-edc', serviceRoute: 'benin-edc', serviceType: "electricity" },
  { serviceName: 'enugu-edc', serviceRoute: 'enugu-edc', serviceType: "electricity" },
  { serviceName: 'eko-edc', serviceRoute: 'eko-edc', serviceType: "electricity" },
  { serviceName: 'ibadan-edc', serviceRoute: 'ibadan-edc', serviceType: "electricity" },
  { serviceName: 'ikeja-edc', serviceRoute: 'ikeja-edc', serviceType: "electricity" },
  { serviceName: 'jos-edc', serviceRoute: 'jos-edc', serviceType: "electricity" },
  { serviceName: 'kaduna-edc', serviceRoute: 'kaduna-edc', serviceType: "electricity" },
  { serviceName: 'abuja-edc', serviceRoute: 'abuja-edc', serviceType: "electricity" },
  { serviceName: 'kedco', serviceRoute: 'kedco', serviceType: "electricity" },
  { serviceName: 'phed-postpaid', serviceRoute: 'phed-postpaid', serviceType: "electricity" },
]

export const PACKAGE: Package[] = [
  {packageName: "Ngn500 Mobile Pin", packageAmount: 500, packageType: "spectranet-limited",},
  {packageName: "gn1000 Mobile Pin", packageAmount: 1000, packageType: "spectranet-limited"},
  {packageName: "Ngn2000 Mobile Pin", packageAmount: 2000, packageType: "spectranet-limited"},
  {packageName: "Ngn5000 Mobile Pin", packageAmount: 5000, packageType: "spectranet-limited"},
  {packageName: "gn7000 Mobile Pin", packageAmount: 7000, packageType: "spectranet-limited"},
  {packageName: "Ngn10000 Mobile Pin", packageAmount: 10000, packageType: "spectranet-limited"},

  {packageName: "1gb Flexidaily (1 Day)", packageAmount: 300, packageType: "smile-bundle"},
  {packageName: "2.5gb Flexidaily (2 Days)", packageAmount: 500, packageType: "smile-bundle"},
  {packageName: "1gb Flexiweekly (7 Days)", packageAmount: 500, packageType: "smile-bundle"},
  {packageName: "Smilevoice Only 65 (30 Days)", packageAmount: 510, packageType: "smile-bundle"},
  {packageName: "1.5gb Bigga (30 Days)", packageAmount: 1000, packageType: "smile-bundle"},
  {packageName: "2gb Flexiweekly (7 Days)", packageAmount: 1000, packageType: "smile-bundle"},
  {packageName: "Smilevoice Only 135 (30 Days)", packageAmount: 1020, packageType: "smile-bundle"},
  {packageName: "2gb Midnite (7 Days)", packageAmount: 1020, packageType: "smile-bundle"},
  {packageName: "2gb Bigga (30 Days)", packageAmount: 1200, packageType: "smile-bundle"},
  {packageName: "3gb Bigga (30 Days)", packageAmount: 1500, packageType: "smile-bundle"},
  {packageName: "6gb Flexiweekly (7 Days)", packageAmount: 1500, packageType: "smile-bundle"},
  {packageName: "3gb Midnite (7 Days)", packageAmount: 1530, packageType: "smile-bundle"},
  {packageName: "3gb Weekend Only (3 Days)", packageAmount: 1530, packageType: "smile-bundle"},
  {packageName: "5gb Bigga (30 Days)", packageAmount: 2000, packageType: "smile-bundle"},
  {packageName: "6.5gb Bigga (30 Days)", packageAmount: 2500, packageType: "smile-bundle"},
  {packageName: "8gb Bigga (30 Days)", packageAmount: 3000, packageType: "smile-bundle"},
  {packageName: "smilevoice Only 430 (30 Days)", packageAmount: 3070, packageType: "smile-bundle"},
  {packageName: "10gb Bigga (30 Days)", packageAmount: 3500, packageType: "smile-bundle"},
  {packageName: "12gb Bigga (30 Days)", packageAmount: 4000, packageType: "smile-bundle"},
  {packageName: "15gb Bigga (30 Days)", packageAmount: 5000, packageType: "smile-bundle"},
  {packageName: "20gb Bigga (30 Days)", packageAmount: 6000, packageType: "smile-bundle"},
  {packageName: "30gb Bigga (30 Days)", packageAmount: 8000, packageType: "smile-bundle"},
  {packageName: "40gb Bigga (30 Days)", packageAmount: 10000, packageType: "smile-bundle"},
  {packageName: "Unlimitedlite (30 Days)", packageAmount: 10000, packageType: "smile-bundle"},
  {packageName: "60gb Bigga (30 Days)", packageAmount: 13500, packageType: "smile-bundle"},
  {packageName: "75gb Bigga (30 Days)", packageAmount: 15000, packageType: "smile-bundle"},
  {packageName: "Unlimitedessential (30 Days)", packageAmount: 15000, packageType: "smile-bundle"},
  {packageName: "100gb Bigga (30 Days)", packageAmount: 18000, packageType: "smile-bundle"},
  {packageName: "90gb Jumbo 20000ngn (60 Days)", packageAmount: 20000, packageType: "smile-bundle"},
  {packageName: "Freedom 3mbps (30 Days)", packageAmount: 20000, packageType: "smile-bundle"},
  {packageName: "Freedom 6mbps (30 Days)", packageAmount: 24000, packageType: "smile-bundle"},
  {packageName: "160gb Jumbo 34000ngn (90 Days)", packageAmount: 34000, packageType: "smile-bundle"},
  {packageName: "Besteffort Freedom (365 Days)", packageAmount: 36000, packageType: "smile-bundle"},
  {packageName: "200gb Jumbo (120 Days)", packageAmount: 40000, packageType: "smile-bundle"},
  {packageName: "125gb 50000ngn (365 Days)", packageAmount: 50000, packageType: "smile-bundle"},
  {packageName: "200gb Anytime (365 Days)", packageAmount: 70000, packageType: "smile-bundle"},
  {packageName: "500gb 100000ngn (365 Days)", packageAmount: 100000, packageType: "smile-bundle"},
  {packageName: "1tb Anytime (365 Days)", packageAmount: 120000, packageType: "smile-bundle"},

  {packageName: "Unlimited Starter Plan", packageAmount: 12900, packageType: "ipnx-subscription-payments"},
  {packageName: "Unlimited Mini Plan", packageAmount: 23115, packageType: "ipnx-subscription-payments"},
  {packageName:"Unlimited Lyte Plan", packageAmount: 17200, packageType: "ipnx-subscription-payments"},
  {packageName: "Unlimited Premium Plan", packageAmount: 62350, packageType: "ipnx-subscription-payments"},
  {packageName: "Unlimited Preferred Plan", packageAmount: 45150, packageType: "ipnx-subscription-payments"},
  {packageName: "Unlimited Basic Plan", packageAmount: 29025, packageType: "ipnx-subscription-payments"},
  {packageName: "Ultimate Premium Plan", packageAmount: 161250, packageType: "ipnx-subscription-payments"},
  {packageName: "Ultimate Preferred Plan", packageAmount: 96750, packageType:"ipnx-subscription-payments"},
  {packageName: "Ultimate Basic Plan", packageAmount: 80625, packageType: "ipnx-subscription-payments"},
  {packageName: "dvantage Premium Plan", packageAmount: 43000, packageType: "ipnx-subscription-payments"},
  {packageName: "Advantage Preferred Plan", packageAmount: 26875, packageType: "ipnx-subscription-payments"},
  {packageName: "Advantage Basic Plan", packageAmount: 16125, packageType: "ipnx-subscription-payments"},
  {packageName: "Starter Preferred Plan", packageAmount: 10750, packageType: "ipnx-subscription-payments"},

  {packageName: "20mb For 1 Day", packageAmount: 25, packageType: "mtn-vtu-plus-data"},
  {packageName: "50mb For 7 Days", packageAmount: 50, packageType: "mtn-vtu-plus-data"},
  {packageName: "100mb For 1 Day", packageAmount: 100, packageType: "mtn-vtu-plus-data"},
  {packageName: "160mb For 30 Days", packageAmount: 150, packageType: "mtn-vtu-plus-data"},
  {packageName: "200mb For 2 Days", packageAmount: 200, packageType: "mtn-vtu-plus-data"},
  {packageName: "350mb For 7 Days", packageAmount: 300, packageType: "mtn-vtu-plus-data"},
  {packageName: "1gb For 1 Day", packageAmount: 300, packageType: "mtn-vtu-plus-data"},
  {packageName: "1gb For 7 Days", packageAmount: 500, packageType: "mtn-vtu-plus-data"},
  {packageName: "2.5gb For 2 Days", packageAmount: 500, packageType: "mtn-vtu-plus-data"},
  {packageName: "750mb For 2 Weeks", packageAmount: 500, packageType: "mtn-vtu-plus-data"},
  {packageName: "1.5gb For 1 Month", packageAmount: 1000, packageType: "mtn-vtu-plus-data"},
  {packageName: "2gb For 1 Month", packageAmount: 1200, packageType: "mtn-vtu-plus-data"},
  {packageName: "3gb For 1 Month", packageAmount: 1500, packageType: "mtn-vtu-plus-data"},
  {packageName: "6gb For 7 Days", packageAmount: 1500, packageType: "mtn-vtu-plus-data"},
  {packageName: "4.5gb For 1 Month", packageAmount: 2000, packageType: "mtn-vtu-plus-data"},
  {packageName: "6gb For 1 Month", packageAmount: 2500, packageType: "mtn-vtu-plus-data"},
  {packageName: "10gb For 1 Month", packageAmount: 3000, packageType: "mtn-vtu-plus-data"},
  {packageName: "12gb For 1 Month", packageAmount: 3500, packageType: "mtn-vtu-plus-data"},
  {packageName: "20gb For 1 Month", packageAmount: 5000, packageType: "mtn-vtu-plus-data"},
  {packageName: "25gb For 1 Month", packageAmount: 6000, packageType: "mtn-vtu-plus-data"},
  {packageName: "40gb For 1 Month", packageAmount: 10000, packageType: "mtn-vtu-plus-data"},
  {packageName: "30gb For 1 Month (sme Data Plan)",packageAmount: 13500, packageType: "mtn-vtu-plus-data"},
  {packageName: "75gb For 1 Month", packageAmount: 15000, packageType: "mtn-vtu-plus-data"},
  {packageName: "110gb For 1 Month", packageAmount: 20000, packageType: "mtn-vtu-plus-data"},
  {packageName: "75gb For 2 Months", packageAmount: 20000, packageType: "mtn-vtu-plus-data"},
  {packageName: "120gb For 2 Months", packageAmount: 30000, packageType: "mtn-vtu-plus-data"},
  {packageName: "90gb For 2 Months (sme Data Plan)", packageAmount: 40000, packageType: "mtn-vtu-plus-data"},
  {packageName: "150gb For 3 Months", packageAmount: 50000, packageType: "mtn-vtu-plus-data"},
  {packageName: "150gb For 3 Month (sme Special Offer)", packageAmount: 50000, packageType: "mtn-vtu-plus-data"},
  {packageName: "250gb For 3 Months", packageAmount: 75000, packageType: "mtn-vtu-plus-data"},
  {packageName: "400gb For 1 Year", packageAmount: 120000, packageType: "mtn-vtu-plus-data"},
  {packageName: "1000gb For 1 Year", packageAmount: 300000, packageType: "mtn-vtu-plus-data"},
  {packageName: "2000gb For 1 Year", packageAmount: 450000, packageType: "mtn-vtu-plus-data"},

  {packageName: "9mobile 25mb (24 Hours)", packageAmount: 50, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 100mb (24 Hours)",packageAmount: 100, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 650mb (24 Hours)", packageAmount: 200, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 500mb (30 Days)", packageAmount: 500, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 1.5gb (30 Days)", packageAmount: 1000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 2gb (30 Days)", packageAmount: 1200, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 7gb (7 Days)", packageAmount: 1500, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 4.5gb (30 Days)", packageAmount: 2000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 11gb (30days)", packageAmount: 4000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 15gb (30 Days)", packageAmount: 5000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 40gb (30 Days)", packageAmount: 10000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 75gb (30 Days)", packageAmount: 15000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 75gb (90 Days)", packageAmount: 25000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 165gb (180 Days)", packageAmount: 50000, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 100gb ( 100 Days)", packageAmount: 84992, packageType: "9Mobile-recharge-e-top-up"},
  {packageName: "9mobile 365gb (365 Days)", packageAmount: 100000, packageType: "9Mobile-recharge-e-top-up"},

  {packageName: "Data Plan Gives 6gb For N1500 Valid For 7days",packageAmount: 1499.03, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 1gb For N300 Valid For 1days", packageAmount: 299.03, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 350mb For N300 Valid For 7day", packageAmount: 299.02, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Monthly Plan - N500(750mb Valid For 14days)", packageAmount: 499, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Monthly Plan - N1,000(1.5gb Valid For 30days)", packageAmount: 999, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan 3gb For N1500 Valid For 30 Days", packageAmount: 1499.01, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 4.5gb For N2000 Valid For 30 Days", packageAmount: 1999, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 11gb For N4000 Valid For 30 Days", packageAmount: 3999.01, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 6gb For N2500 Valid For 30 Days", packageAmount: 2499.01, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 2gb For N500 Valid For 1day", packageAmount: 499.03, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 2gb For N1200 Valid For 30days",packageAmount: 1199, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 40gb For N10000 Valid For 30days", packageAmount: 9999, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 75gb For N15000 Valid For 30days", packageAmount: 14999, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Daily Plan -n50 (40mb Valid For 1 Day)", packageAmount: 49.99, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Daily Plan -n100 (100mb Valid For 1 Day)", packageAmount: 99, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Daily Plan -n200(200mb Valid For 3 Days)",packageAmount: 199.03, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 10gb For N3000 Valid For 30 Days", packageAmount: 2999.02, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 20gb For N5000 Valid For 30 Days", packageAmount: 4999, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 120gb For N20000 Valid For 30 Days", packageAmount: 19999.02, packageType: "airtel-prepaid-data-bundle"},
  {packageName: "Data Plan Gives 200gb For N30000 Valid For 30 Days", packageAmount: 29999.02, packageType: "airtel-prepaid-data-bundle"},

  {packageName: "N2,100 For Calls, Sms &amp; Data (7 Days)", packageAmount: 699, packageType: "airtel-voice-data-sms-bundles"},
  {packageName: "N4,500 For Calls, Sms &amp; Data (15 Days)", packageAmount: 1499, packageType: "airtel-voice-data-sms-bundles"},
  {packageName: "N63,000 Voice + 2,000 Free Sms - All Networks (30 Days)", packageAmount: 19999, packageType: "airtel-voice-data-sms-bundles"},
  {packageName: "N173,000 Airtime + 4,000 Free Sms - All Networks (30 Days)", packageAmount: 49999, packageType: "airtel-voice-data-sms-bundles"},
  {packageName: "N68,000 Airtime + 4gb (30 Days)", packageAmount: 24999, packageType: "airtel-voice-data-sms-bundles"},
  {packageName: "N168,000 Airtime + 6gb (30 Days)", packageAmount: 54999, packageType: "airtel-voice-data-sms-bundles"},

  {packageName: "1gb Night Only", packageAmount: 100, packageType: "glo-data-bundle"},
  {packageName: "150mb For 1 Day", packageAmount: 100, packageType: "glo-data-bundle"},
  {packageName: "350mb For 2 Days", packageAmount: 200, packageType: "glo-data-bundle"},
  {packageName: "500mb Night Only", packageAmount: 50, packageType: "glo-data-bundle"},
  {packageName: "1.25gb (sunday 1 Day)", packageAmount: 200, packageType: "glo-data-bundle"},
  {packageName: "1.35gb For 14 Days", packageAmount: 500, packageType: "glo-data-bundle"},
  {packageName: "2.9gb For 30days", packageAmount: 1000, packageType: "glo-data-bundle"},
  {packageName: "5.8gb For 30 Days", packageAmount: 2000, packageType: "glo-data-bundle"},
  {packageName: "7.7gb For 30days", packageAmount: 2500, packageType: "glo-data-bundle"},
  {packageName: "10gb For 30 Days", packageAmount: 3000, packageType: "glo-data-bundle"},
  {packageName: "13.25gb For 30 Days", packageAmount: 4000, packageType: "glo-data-bundle"},
  {packageName: "18.25gb For 30 Days", packageAmount: 5000, packageType: "glo-data-bundle"},
  {packageName: "29.5gb For 30days", packageAmount: 8000, packageType: "glo-data-bundle"},
  {packageName: "50gb For 30days", packageAmount: 10000, packageType: "glo-data-bundle"},
  {packageName: "93gb For 30days", packageAmount: 15000, packageType: "glo-data-bundle"},
  {packageName: "119gb For 30days", packageAmount: 18000, packageType: "glo-data-bundle"},
  {packageName: "50mb For 1day", packageAmount: 50, packageType: "glo-data-bundle"},
  {packageName: "138gb For 30days", packageAmount: 20000, packageType: "glo-data-bundle"},
  {packageName: "7gb For 7days", packageAmount: 1500, packageType: "glo-data-bundle"},
  {packageName: "4.1gb For 30days", packageAmount: 1500, packageType: "glo-data-bundle"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "benin-edc"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "benin-edc"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "eko-ed"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "eko-edc"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "enugu-edc"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "enugu-edc"},

  {packageName: "Electric Bill", packageAmount: 0, packageType: "ibadan-edc"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "ibadan-edc"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "ikeja-edc"},
  {packageName: "Prepaid", packageAmount: 0 , packageType: "ikeja-edc"},

  {packageName: "Jedc Postpaid", packageAmount: 0, packageType: "jos-edc"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "jos-edc"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "kaduna-edc"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "kaduna-edc"},

  {packageName: "Aedc Postpaid", packageAmount: 0, packageType: "abuja-edc"},
  {packageName: "Aedc Prepaid", packageAmount: 0, packageType: "abuja-edc"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "kedco"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "kedco"},

  {packageName: "Postpaid", packageAmount: 0, packageType: "phed-postpaid"},
  {packageName: "Prepaid", packageAmount: 0, packageType: "phed-postpaid"}

]
